INSERT INTO TB_PESSOA (ID_PESSOA, NOME, SOBRE_NOME, IDADE, ATIVO) VALUES (1, 'Maikon', 'Canuto', 21, TRUE);

INSERT INTO TB_USUARIO (ID_USUARIO, NO_USUARIO, SENHA, ATIVO) VALUES (1, 'maikoncanuto', '123', TRUE);