INSERT INTO PESSOA (COD_PESSOA, NOME, SOBRE_NOME, IDADE) VALUES (1, 'Maikon', 'Canuto', 21);
INSERT INTO PESSOA (COD_PESSOA, NOME, SOBRE_NOME, IDADE) VALUES (2, 'Jéssica', 'Silva', 22);
INSERT INTO PESSOA (COD_PESSOA, NOME, SOBRE_NOME, IDADE) VALUES (3, 'Carlos', 'Carvalho', 12);
INSERT INTO PESSOA (COD_PESSOA, NOME, SOBRE_NOME, IDADE) VALUES (4, 'Guilherme', 'Santos', 31);
INSERT INTO PESSOA (COD_PESSOA, NOME, SOBRE_NOME, IDADE) VALUES (5, 'Chaynne', 'Pedrosa', 45);
INSERT INTO PESSOA (COD_PESSOA, NOME, SOBRE_NOME, IDADE) VALUES (6, 'Cassandra', 'Fernandes', 48);
INSERT INTO PESSOA (COD_PESSOA, NOME, SOBRE_NOME, IDADE) VALUES (7, 'Flávia', 'Teles', 39);
INSERT INTO PESSOA (COD_PESSOA, NOME, SOBRE_NOME, IDADE) VALUES (8, 'Andressa', 'Pessoa', 50);